# Use the official Nginx image
FROM nginx

# Expose port 80
EXPOSE 80

# Copy the application files into the container
COPY . /var/www/html

# Copy Nginx configuration file into the container
COPY nginx.conf /etc/nginx/nginx.conf
