version: '3.7'
services:
  nakedDb:
    image: mysql:latest
    container_name: nakedDb
    environment:
      MYSQL_ROOT_PASSWORD: '1q2w3e4r'
      MYSQL_DATABASE: 'tyr-db'
      MYSQL_USER: 'ironman'
      MYSQL_PASSWORD: '1q2w3e4r'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  naked-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: naked-phpmyadmin
    environment:
      PMA_HOST: nakedDb
      PMA_PORT: 3306
    ports:
      - "8090:80"
    depends_on:
      - nakedDb

  naked-app:
    build: 
      context: .
      dockerfile: Dockerfile.apache
    container_name: naked-app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - nakedDb
    environment:
      - MYSQL_HOST=nakedDb
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=web-app
      - MYSQL_USER=ironman
      - MYSQL_PASSWORD=1q2w3e4r
    command: >
      bash -c "apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo_mysql && apache2-foreground"

networks:
  naked-network:
    driver: bridge

volumes:
  mysql_data:
