# Use the official php:7.4-fpm image
FROM php:7.4-fpm

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
        libpq-dev \
        && \
    rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_mysql
